### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by Smurfy98** [inconvergent/cl-veq#1]
First of all: I like your projects, they are very interesting!

I would be really happy if you could describe what the functions do somewhere and what their names mean. For example "f2$+". I just can't find anywhere a notation definition.

**Comment by inconvergent** [comment]
there is certainly room for more documentation. but i have not made it my priority. i am currently making some other larger changes. however, there is an example of use for some function named `f3$+` in the examples file. the other fx names with `$[operator]` in them perform similar broadcasting ("for every row") operations.

**Comment by Smurfy98** [comment]
Yes I saw the usage but it certainly does not explain what it does. It might be obvious to you, as you developed it, but as someone trying to use "weird" it's a bit problematic that there is no explanation at all.


What are fx functions? What are broadcasts? What do the operators mean?

**Comment by inconvergent** [comment]
i appreciate that you are trying to use weird. but i don't have the time to write docs for this now. 

as for `f3$+`, the explanation in the example file is pretty clear i think: 

```
; add 1 to every row of a
(vpr (f3$+ a (f3rep 1f0)))
```
the naming scheme is `[f for float, d for double][dim][$ if it pertains to arrays][fx/operation name, such as + or norm]`. 

in any case. docs might show up eventually. but not now, unfortunately.
