### ISSUE TITLE
Refernce to sb-ext make "veq/tests" it fail to compile on other platforms

### ISSUE THREAD

**Issue by Yehouda** [inconvergent/cl-veq#3]
https://github.com/inconvergent/cl-veq/blob/61c4a8024c4197dc999baf302be36dcbb2e60ea2/test/run.lisp#L21

I suggest you replace it by **uiop:quit**:        
```
 (uiop:quit 7)
```

BTW: the current code relies on being in the right directory when running the tests. It is better to make the paths relative to the system, using **asdf:system-relatve-pathname**, for example: 
```
(defparameter *files* 
  (mapcar #'(lambda(relative-path)
              (asdf:system-relative-pathname "veq/tests" relative-path))
          `(#P"test/veq.lisp" #P"test/macro.lisp" #P"test/arr-with.lisp"
                              #P"test/arr.lisp" #P"test/checks.lisp" #P"test/mat.lisp")))
```

**Comment by inconvergent** [comment]
@Yehouda thank you, i will try to alter this shortly

**Comment by inconvergent** [comment]
@Yehouda i made the changes you suggested now. it is included in this commit that contains some other cleaning. https://github.com/inconvergent/cl-veq/commit/3ed11677b4bea46a2456ec69ad8c10ba48b8c7e9
