### ISSUE TITLE
illegal OF-TYPE in COLLECT inside LOOP

### ISSUE THREAD

**Issue by Yehouda** [inconvergent/cl-veq#4]
https://github.com/inconvergent/cl-veq/blob/1cf5088d1d900cf1a3cea567976218cf05c9bc00/src/lets.lisp#L80
the **of-type** in the line above is invalid, because **collect** does not take a type spec according to the stanrd of [loop](http://www.lispworks.com/documentation/lw50/CLHS/Body/m_loop.htm). Maybe some implementation don't error on taht, but LispWorks at least does. 

It needs to simply be removed.

**Comment by inconvergent** [comment]
i removed it in https://github.com/inconvergent/cl-veq/commit/d3b64d1b4b98bd7543363bda21bf887a3516fbbe
